[frontends.tcp_9000]
listen_addr = "0.0.0.0:9000"
backend = "tcp9000_out"

[backends.tcp9000_out]
  health_check_interval = 3
  [backends.tcp9000_out.servers]
    [backends.tcp9000_out.servers.server1]
    addr = "192.168.1.123:3030"
    weight = 1
    [backends.tcp9000_out.servers.server2]
    addr = "192.168.1.45:3030"
    weight = 1
    [backends.tcp9000_out.servers.server3]
    addr = "192.168.1.123:3031"
    weight = 1
    [backends.tcp9000_out.servers.server4]
    addr = "192.168.1.45:3031"
    weight = 1


[stats]
port = "7000"
