- name: mirror the unikernel images to each node
  copy:
    src: "{{ user_dir }}/.ops/images/{{ item.image }}"
    dest: "{{ user_dir }}/.ops/images/{{ item.image }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ instances }}"
  tags: deploy

- name: create unikernel instance on each node
  command: "ops instance create -p {{ item.port }} -i {{ item.instance }} {{ item.image }}"
  async: 5
  poll: 5
  register: instance
  with_items: "{{ instances }}" 
  tags: deploy

- debug: 
    var: instance
  tags: deploy

- name: stop all unikernel instances 
  command: "ops instance delete {{ item.instance }}"
  async: 5
  poll: 5
  register: instance_stop
  with_items: "{{ instances }}" 
  tags: stop

- debug: 
    var: instance_stop
  tags: stop

- name: copy raw binary files to each node
  copy:
    src: "{{ user_dir }}/{{ project_dir }}/{{ item.name }}/target/release/{{ item.name }}"
    dest: "{{ user_dir }}/{{ item.name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ repos }}"
  tags: deploy-raw

- name: start each instance of the raw binary on each node
  command: "{{ user_dir }}/{{ item.name }} &"
  async: 5
  poll: 5
  register: instance-raw
  with_items: "{{ instances }}" 
  tags: deploy-na

- debug: 
    var: instance-raw
  tags: deploy-raw

- name: stop all raw binary instances 
  shell: "kill -9 $(ps -ef | grep -v grep | grep {{ item.instance }} | awk '{print $2}')"
  async: 5
  poll: 5
  register: instance_stop
  with_items: "{{ instances }}" 
  tags: stop-raw

