---
- hosts: srva
  vars_files:
    - roles/certs/vars/server-a.yml
  roles:
    - certs

- hosts: srvb
  vars_files:
    - roles/certs/vars/server-b.yml
  roles:
    - certs

- hosts: srvc
  vars_files:
    - roles/certs/vars/server-c.yml
  roles:
    - certs

